### ISSUE TITLE
It doesnt extract key

### ISSUE THREAD

**Issue by moderator007tech** [pozm/gdke#1]
Failed to get key: Failed to find key.  Im using the 3week old version. Im using the gui on a .exe file

**Comment by pozm** [comment]
Could you provide some info such as:
- The exact godot version (run the game with --version in the cli)
- Link to where i can find and download the game

**Comment by moderator007tech** [comment]
hi godot version is 3.4.2 ;   whats your discord, ill send you a message

**Comment by pozm** [comment]
Aixeria#0001

**Comment by pozm** [comment]
resolved in latest release (https://github.com/pozm/gdke/releases/tag/0.1.3)
