### ISSUE TITLE
fail to extract key

### ISSUE THREAD

**Issue by 2717753650** [pozm/gdke#4]
i use it to extract a game key but failed the game godot version i think is 2.1

**Comment by pozm** [comment]
You can find what godot version the game is using by opening properties and then going to details and then file version.

here's an example: 
![image](https://github.com/pozm/gdke/assets/44528100/c6ecff3a-7e15-4fb6-a9eb-5c1aab29a46c)
![image](https://github.com/pozm/gdke/assets/44528100/5c013ac4-7793-48aa-b995-e904b0a27992)

**Comment by 2717753650** [comment]
thank you,i found the version is 2.1.7.0,a old version maybe it’s the reason why it doesn’t work?

**Comment by pozm** [comment]
Yeah this is why, but this is completely fine and normal. The way which the program finds the key is through signatures. so if code changes the signature will be different (this is also same with different compilers). I'll look into building the version or finding a godot template with this version and i'll get back to you.

**Comment by 2717753650** [comment]
Thank you for your help.

**Comment by 2717753650** [comment]
![image](https://github.com/pozm/gdke/assets/73518494/ebfc9919-d86c-4bd1-afdd-6ced08f49141)

**Comment by 2717753650** [comment]
I have a question. I tried to extract the key manually following your tutorial. Your tutorial is good, and I followed the steps to the final stage. However, I don't know how to follow the offset and read the bytes. Could you provide more detailed instructions? I would greatly appreciate your help.

**Comment by pozm** [comment]
You should just be able to double click on `unk_141018F10` and it will take you to .data section where the key is stored.
if it's not already detected as an array, you can select 32 elements and then covert it to an array and then export the data (menubar -> Edit -> Export data)

**Comment by 2717753650** [comment]
![image](https://github.com/pozm/gdke/assets/73518494/3c18da35-47d2-44b9-add1-fad22aca0cbb)

Thank you, your tutorial is very useful. Actually, I used the same method to find the key, but I am not sure if it's correct because I failed to decompile the .gde file with the key using gdre_tools. It might be a problem with gdre_tools.
